version: '3.1'

services:
  mysql-datamint:
    image: mysql:latest
    environment:
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
networks:
  default:
      name: datamint-mysql